/*Populate Users Data*/
INSERT INTO Users (email, password, username, first_name, last_name, is_admin)
VALUES ('prachan.ghale@example.com', 'password123', 'prachanghale', 'Prachan', 'Ghale', TRUE),
       ('sandip.moktan@example.com', 'password123', 'sandipmoktan', 'Sandip', 'Moktan', FALSE),
       ('anchal.gurung@example.com', 'password123', 'anchalgurung', 'Anchal', 'Gurung', FALSE),
       ('nigam.bhattarai@example.com', 'password123', 'nigambhattarai', 'Nigam', 'Bhattarai', FALSE),
       ('alisha.shrestha@example.com', 'password123', 'alishashrestha', 'Alisha', 'Shrestha', FALSE);

-- Populate Categories
INSERT INTO Categories (category_name)
VALUES ('Appetizers'),
       ('Main Courses'),
       ('Soups & Stews'),
       ('Salads'),
       ('Side Dishes'),
       ('Desserts'),
       ('Breakfast'),
       ('Beverages'),
       ('Sauces & Condiments'),
       ('Baking'),
       ('Healthy Eating'),
       ('International Cuisine'),
       ('Holiday & Special Occasions'),
       ('Comfort Food'),
       ('One-Pot Meals'),
       ('Vegetarian'),
       ('Vegan'),
       ('Gluten-Free'),
       ('Low-Carb'),
       ('Quick & Easy'),
       ('Kids’ Favorites'),
       ('Pasta Dishes'),
       ('Seafood'),
       ('Poultry'),
       ('Beef'),
       ('Pork'),
       ('Grilling & BBQ'),
       ('Slow Cooker'),
       ('Mediterranean'),
       ('Asian'),
       ('Mexican'),
       ('Italian'),
       ('French'),
       ('Indian'),
       ('Middle Eastern'),
       ('American Classics'),
       ('Farm-to-Table'),
       ('Street Food'),
       ('Gourmet'),
       ('Casseroles');

-- Populate Recipe
INSERT INTO Recipes (user_id, title, description, image, video_url, created_at, updated_at)
VALUES (107, 'Spaghetti Carbonara', 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
        'dbimages/20240805011246_992.JPG', 'https://example.com/carbonara', NOW(), NOW()),
       (107, 'Chicken Alfredo', 'Creamy pasta dish with chicken and parmesan cheese.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/alfredo', NOW(), NOW()),
       (107, 'Beef Stroganoff', 'Tender beef strips in a creamy mushroom sauce.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/stroganoff', NOW(), NOW()),
       (107, 'Vegetable Stir Fry', 'A mix of fresh vegetables stir-fried with soy sauce and garlic.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/stirfry', NOW(), NOW()),
       (107, 'Margherita Pizza', 'Classic pizza topped with tomato sauce, mozzarella cheese, and basil.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/pizza', NOW(), NOW()),
       (107, 'Caesar Salad', 'Crisp romaine lettuce with Caesar dressing, croutons, and parmesan cheese.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/caesar', NOW(), NOW()),
       (107, 'Beef Tacos', 'Tacos filled with seasoned ground beef, lettuce, and cheese.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/tacos', NOW(), NOW()),
       (107, 'Chicken Curry', 'Spicy and flavorful chicken curry with a blend of Indian spices.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/curry', NOW(), NOW()),
       (107, 'Greek Salad', 'A fresh salad with cucumbers, tomatoes, olives, feta cheese, and red onions.',
        'dbimages/20240805011246_992.JPG', 'https://example.com/greeksalad', NOW(), NOW()),
       (107, 'Lemon Drizzle Cake', 'A moist cake with a tangy lemon glaze.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/lemoncake', NOW(), NOW()),
       (107, 'Pancakes', 'Fluffy pancakes served with maple syrup and butter.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/pancakes', NOW(), NOW()),
       (107, 'Lasagna', 'Layers of pasta, meat sauce, and cheese baked to perfection.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/lasagna', NOW(), NOW()),
       (107, 'Vegetable Soup', 'A hearty soup filled with various fresh vegetables.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/soup', NOW(), NOW()),
       (107, 'BBQ Ribs', 'Tender ribs cooked with a smoky BBQ sauce.', 'dbimages/20240805011246_992.JPG', 'https://example.com/ribs', NOW(),
        NOW()),
       (107, 'Apple Pie', 'Classic apple pie with a buttery crust and sweet apple filling.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/applepie', NOW(), NOW()),
       (107, 'Fish Tacos', 'Tacos made with seasoned fish, cabbage slaw, and a creamy sauce.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/fishtacos', NOW(), NOW()),
       (107, 'Quiche Lorraine', 'Savory pie filled with bacon, eggs, and cheese.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/quiche', NOW(), NOW()),
       (107, 'Stuffed Bell Peppers', 'Bell peppers filled with a mixture of ground meat, rice, and vegetables.',
        'dbimages/20240805011246_992.JPG', 'https://example.com/stuffedpeppers', NOW(), NOW()),
       (107, 'Chicken Caesar Wrap', 'Grilled chicken wrapped with Caesar salad ingredients.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/wrap', NOW(), NOW()),
       (107, 'Brownies', 'Fudgy chocolate brownies with a crispy top.', 'dbimages/20240805011246_992.JPG', 'https://example.com/brownies',
        NOW(), NOW()),
       (107, 'Mushroom Risotto', 'Creamy risotto with sautéed mushrooms and parmesan cheese.', 'dbimages/20240805011246_992.JPG',
        'https://example.com/risotto', NOW(), NOW()),
       (107, 'Chili Con Carne', 'Spicy beef chili with beans and tomatoes.', 'dbimages/20240805011246_992.JPG', 'https://example.com/chili',
        NOW(), NOW());

UPDATE Recipes SET image = 'dbimages/20240805011246_992.JPG' WHERE recipes.user_id = 107;


SELECT COUNT(*) FROM users WHERE is_admin = false AND status = 'ACTIVE';